version: '2.0'
services:
    LinuxDesktopMate:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: docker-linux-desktop:mate
        container_name: docker-linux-desktop-mate
        volumes:
            - $HOME/.docker-home-dir:/home
        ports:
        - "3389:3389"
